require:

  - 'rubocop'

AllCops:

  TargetRubyVersion: 3.0.1
  NewCops: enable

  Exclude:

  - 'executed_files/**/*'
  - 'processing_files/**/*'
  - 'return_files/**/*'
  - 'spec/spec_helper.rb'

Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'it']
Metrics/ClassLength:
  Exclude:
    - 'spec/**/*'